### ISSUE TITLE
Wrong order of concatanation

### ISSUE THREAD

**Issue by pYtoner** [blockfrost/blockfrost-rust#35]
In the [all_requests.rs](https://github.com/blockfrost/blockfrost-rust/blob/master/examples/all_requests.rs) line 48

I think the `policy_id` and `asset_name` are in the wrong order. 
https://docs.blockfrost.io/#tag/Cardano-Assets/paths/~1assets~1{asset}/get
says that asset is
>Concatenation of the policy_id and hex-encoded asset_name

```
let asset = asset_name.to_string() + policy_id;
```
Should be:
```
let asset = policy_id + asset_name.to_string();
```

**Comment by vladimirvolek** [comment]
This is correct.
You can check asset and policyId at https://cardano-tokens.com

https://cardano-mainnet.blockfrost.io/api/v0/assets/00000002df633853f6a47465c9496721d2d5b1291b8398016c0e87ae6e7574636f696e/history
```
[
  {
    "tx_hash": "e252be4c7e40d35919f741c9649ff207c3e49d53bb819e5c1cb458055fd363ed",
    "action": "minted",
    "amount": "1"
  }
```
